config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  
  get '/auth/facebook/callback' => 'sessions#create'

  resources :assignments, :only => [:show, :index, :edit, :new, :create, :update]

  resources :parents, :only => [:show, :new, :edit, :create, :update]

  resources :children, :only => [:show, :index, :edit, :new, :create, :update]

  resources :classrooms, :only => [:show, :index, :edit, :new, :create, :update]
  resources :classrooms, :only => [:show] do 
    resources :children, :only => [:show, :index, :new, :edit]
  end

  resources :teachers, :only => [:show, :index, :edit, :new, :create, :update]
  resources :teachers, :only => [:show, :index] do 
    resources :assignments, :only => [:show, :index, :new, :edit, :update]
  end


  get '/children/search', to:'children#search'
  post '/children/search', to:'children#results'

  end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  layout "openapp"
  before_action :set_child, :only => [:show, :edit, :update]
  before_action :authentication_required
  before_action :redirect_if_not_authorized, :only => [:edit, :update]

  def show
  end

  def index
    if params[:classroom_id]
      @children = Classroom.find(params[:classroom_id]).children
    else
    @children = Child.all
    end
  end

  def new
    if params[:classroom_id] && !Classroom.exists?(params[:classroom_id])
      redirect_to classrooms_path, alert: "Classroom not found."
    else
      @child = Child.new(classroom_id: params[:classroom_id])
    end
  end

  def edit
    if params[:classroom_id]
      classroom = Classroom.find_by(id: params[:classroom_id])
      if classroom.nil?
        redirect_to classrooms_path, alert: "Classroom not found."
      else
        @child = classroom.children.find_by(id: params[:id])
        redirect_to classroom_children_path(classroom), alert: "Student not found." if @child.nil?
      end
    end
  end

  def create
    @child = Child.new(child_params)
    if @child.save
      redirect_to @child
    else
      render:new
    end
  end
  
  def update
    if @child.update(child_params)
      redirect_to @child
    else
      render:edit
    end
  end

  def parent_name=(name)
    byebug
    self.parent = Parent.find_or_create_by(first_name: first_name)
  end
  

  def parent_name
     self.parent ? self.parent.name : nil
  end 

  def classroom_name=(name)
    self.classroom = Classroom.find_by(title: name)
  end

  def classroom_name
    self.classroom ? self.classroom.name : nil
  end

  def search
  end

  def results
    @children = Child.search(params[:query])
    render :index
  end

  private

  def set_child
    @child = Child.find(params[:id])
  end

  def child_params
    params.require(:child).permit(:first_name, :last_name, :age, :favorite_color, :classroom_id, :parent_id, :search)
  end

  def redirect_if_not_authorized
    if current_user.id != @child.classroom.teacher.id
        redirect_to child_path(@child)
    end
  end

end 

app/helpers/children_helper.rb
module ChildrenHelper
    def children_for_select
        Child.all.collect { |c| [c.to_s, c.id] }
    end
end

app/views/children/_children.html.erb
<% classroom_children.each do |c| %>
    <li><div><%= link_to c.first_name, child_path(c) %>, age <%= c.age%></div></li><br>
<% end %>

app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
    <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@child.errors.count, "error") %>
        prohibited this student from being saved:
      </h2> 
   
      <ul>
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul></div>
    <% end %>

    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %><br><br>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %><br><br>
    <%= f.label :age %><br>
    <%= f.number_field :age %><br><br>
    <%= f.label :favorite_color %><br>
    <%= f.text_field :favorite_color%><br><br>
    <%= f.collection_select :classroom_id, Classroom.all.order('title ASC'), :id, :title, { prompt: 'Select a Classroom' }, { id: 'classroom_select' } %><br><br>
    <%= f.submit class: "btn btn-primary" %><br><br>
<% end %> 

app/views/children/_search.html.erb
<%= form_with url:"/children/search", local: :true  do |form| %>
    <%= form.label "Search by Last Name: "%>
    <%= form.text_field :query%>
    <%= form.submit "Search"%>
<% end %>

app/views/children/edit.html.erb
<h1>Edit <%= @child.first_name %>'s Info Page</h1>
<%= render 'form' %>

app/views/children/index.html.erb
<%= render partial: 'search'%>
<h2> All Students: </h2>
<i>Ordered by last name:</i>
<ul>
<% @children.each do |c| %>
    <div><%= link_to c.to_s, child_path(c) %>, age: <%=c.age%> </div><br>
<% end %>
</ul><br><br>

<i><%= link_to 'New Student', new_classroom_child_path(@children) %></i><br><br> 

app/views/children/new.html.erb
<h1> Add a Student </h1>
<%= render 'form' %>

app/views/children/show.html.erb
<h1><%= @child.to_s %>'s Info Page</h1>
<hr>
<h3>Full Name: <%= @child.to_s %></h3>
<% if @child.parent.nil? %>
<p><i>This student does not currently have a Parent listed, please <%= link_to 'edit', new_parent_path(@child) %> to update.</i></p>
<% else %>
<h3><%= link_to 'Parent Contact Info', parent_path(@child.parent)%></h3>
<% end %><p>Age: <%= @child.age %></p>
<p>Favorite Color: <%= @child.favorite_color %></p><br><br><br>
<p><strong> Class: <%= link_to @child.classroom.title, classroom_path(@child.classroom) %></strong></p>
<p><strong> Teacher: <%= link_to @child.classroom.teacher.to_s, teacher_path(@child.classroom.teacher) %></strong></p><br>

<p>Upcoming Assignments: 
<% @child.assignments_children.each do |a| %>
    <div><li><%= link_to a.assignment.title, assignment_path(a) %>, due <%= a.assignment.due_date.utc.getlocal.strftime("%A, %b %e, at %I:%M  %p ")%></li></div><br>
<% end %> </p><br>
<p><i><%= @child.last_updated %></i></p>
<p><%= link_to 'Edit Student', edit_classroom_child_path(@child) %></p>