config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  
  get '/auth/facebook/callback' => 'sessions#create'

  resources :assignments, :only => [:show, :index, :edit, :new, :create, :update]

  resources :parents, :only => [:show, :new, :edit, :create, :update]

  resources :children, :only => [:show, :index, :edit, :new, :create, :update]

  resources :classrooms, :only => [:show, :index, :edit, :new, :create, :update]
  resources :classrooms, :only => [:show] do 
    resources :children, :only => [:show, :index, :new, :edit]
  end

  resources :teachers, :only => [:show, :index, :edit, :new, :create, :update]
  resources :teachers, :only => [:show, :index] do 
    resources :assignments, :only => [:show, :index, :new, :edit, :update]
  end


  get '/children/search', to:'children#search'
  post '/children/search', to:'children#results'

  end

app/models/assignment.rb
class Assignment < ApplicationRecord
    belongs_to :teacher
    has_many :assignments_children, :class_name => 'AssignmentsChildren'
    has_many :children, through: :assignments_children
    accepts_nested_attributes_for :assignments_children

    validates :title, :presence => true
    validates :description, :presence => true
    validates :due_date, :presence => true

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  layout "openapp"
  before_action :set_assignment, :only => [:show, :edit, :update]
  before_action :authentication_required, :only => [:show, :index, :edit, :update, :new, :create]

  def show
  end

  def index
    if params[:teacher_id]
      @assignments = Teacher.find(params[:teacher_id]).assignments
    else
    @assignments = Assignment.all
    end
  end

  def new
    if params[:teacher_id] && !Teacher.exists?(params[:teacher_id])
      redirect_to teachers_path, alert: "Teacher not found."
    else
      @assignment = Assignment.new(teacher_id: params[:teacher_id])
    end
  end

  def edit
    if params[:teacher_id]
      teacher = Teacher.find_by(id: params[:teacher_id])
      if teacher.nil?
        redirect_to teacher_path, alert: "Teacher not found."
      else 
        @assignment = teacher.assignments.find_by(id: params[:id])
        redirect_to teacher_assignments_path(teacher), alert: "Assignment not found." if @assignment.nil?
      end
    end
  end

  def create
    @assignment = Assignment.new(assign_params)
    if @assignment.save
      redirect_to @assignment
    else 
      render:new
    end
  end

  def update
    if @assignment.update(assign_params)
      redirect_to @assignment
    else 
      render:edit
    end
  end

  private

  def set_assignment
    @assignment = Assignment.find(params[:id])
  end

  def assign_params
    params.require(:assignment).permit(:title, :description, :due_date, :teacher_id, child_ids:[], children_attributes: [:first_name, :last_name])
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
    def teacher_id_field(assignment)
        if assignment.teacher.nil?
          select_tag "assignment[teacher_id]", options_from_collection_for_select(Teacher.all, :id, :to_s)
        else
          hidden_field_tag "assignment[teacher_id]", assignment.teacher_id
        end
      end
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <%= teacher_id_field(@assignment) %>
    <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@assignment.errors.count, "error") %>
        prohibited this assignment from being saved:
      </h2>
   
      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul></div>
    <% end %>

    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>
    <%= f.label :description %><br>
    <%= f.text_field :description %><br><br>
    <%= f.label :due_date %><br><br>
    <%= f.datetime_local_field :due_date %><br><br>
    <%= f.collection_select :teacher_id, Teacher.all.order('last_name ASC'), :id, :to_s, { prompt: 'Select a Teacher' }, { id: 'teachers_select' } %><br><br><br>
    <%= f.collection_check_boxes :child_ids, Child.all , :id, :to_s%><br><br>
    <%= f.check_box :complete %>
    <%= f.label :complete, "Check box if assignment is complete." %><br><br>
    
    <%= f.submit class: "btn btn-primary" %><br><br>
<% end %> 

app/views/assignments/edit.html.erb
<h1>Edit Assignment: <%= @assignment.title %></h1>
<%= render 'form' %>

app/views/assignments/index.html.erb
<h1>Assignments</h1>
<% @assignments.each do |a| %>
    <li><%= link_to a.title, assignment_path(a) %></li>
<% end %><br><br>
<i><%= link_to 'New Assignment', new_teacher_assignment_path(@current_user) %></i><br><br>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>
<%= render 'form' %>

app/views/assignments/show.html.erb
<h1>Assignment: <%=@assignment.title%></h1>
<hr>
<h4>Description: <%=@assignment.description%></h4><br>
<% if @assignment.assignments_children.empty? %>
<p><i>There are currently no students assigned to this assignment. </i></p>
<% else %>
<h4>Students Assigned: </h4>
<% @assignment.assignments_children.each do |a| %>
    <div><li><%= link_to a.child.to_s, child_path(a.child) %></li></div>
<% end %> </p><br>
<% end %>
<p><%= link_to 'Edit Assignment', edit_teacher_assignment_path(@assignment) %></p>
<p><i><%= @assignment.last_updated %></i></p>