config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  
  get '/auth/facebook/callback' => 'sessions#create'

  resources :assignments, :only => [:show, :index, :edit, :new, :create, :update]

  resources :parents, :only => [:show, :new, :edit, :create, :update]

  resources :children, :only => [:show, :index, :edit, :new, :create, :update]

  resources :classrooms, :only => [:show, :index, :edit, :new, :create, :update]
  resources :classrooms, :only => [:show] do 
    resources :children, :only => [:show, :index, :new, :edit]
  end

  resources :teachers, :only => [:show, :index, :edit, :new, :create, :update]
  resources :teachers, :only => [:show, :index] do 
    resources :assignments, :only => [:show, :index, :new, :edit, :update]
  end


  get '/children/search', to:'children#search'
  post '/children/search', to:'children#results'

  end

app/models/teacher.rb
class Teacher < ApplicationRecord
    include ActiveModel::Validations

    has_secure_password
    
    has_one :classroom
    has_many :children, :through => :classroom
    has_many :assignments

    validates :first_name, :presence => true
    validates :last_name, :presence => true
    validates :phone_number, length: { is: 10 }
    validates :dl, length: { is: 8 }
    validates :volunteer, inclusion: [true, false]
    validates :email, presence: true, email: true, uniqueness: true
    validates :password, length: { in: 6..20 }

    def self.find_or_create_by_omniauth(auth)
        self.where(:email => auth["info"]["email"]).first_or_create do |user|
            user.password = SecureRandom.hex
        end
    end
    def list_all_teachers
        Teacher.all.sort{|a,b| a.last_name <=> b.last_name}.each_with_index do |teacher,i|
            "#{i+1}. #{teacher.name}"
        end
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  layout :resolve_layout
  before_action :set_teacher, :only => [:show, :edit, :update, :assignment_index, :assignment]
  before_action :authentication_required, :only => [:show, :index, :edit, :update]
  before_action :redirect_if_not_authorized, :only => [:edit, :update]

  def show
  end

  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end
  
  def edit
  end
  
  def create 
    @teacher = Teacher.new(teach_params)
    if @teacher.save
      redirect_to teacher_path(@teacher)
    else 
      render:new
    end
  end

  def update
    if @teacher.update(teach_params)
      redirect_to @teacher
    else
      render:edit
    end
  end

  def assignment_index
    @assignments = Teacher.assignments
    render template: 'assignments/index'
  end

  def assignment
    @assignment = Assignment.find(params[:assignment_id])
    render template: 'assignments/show'
  end

  def resolve_layout
    case action_name
    when "new", "create"
      "application"
    when "show", "edit", "update", "index"
      "openapp"
    else
      "application"
    end
  end
  
  private

  def set_teacher
    @teacher = Teacher.find_by_id(params[:id])
  end

  def require_login
    return head(:forbidden) unless session.include? :teacher_id
  end

  def redirect_if_not_authorized
    if current_user.id != @teacher.id
        redirect_to teacher_path(@teacher)
    end
  end

  def teach_params
    params.require(:teacher).permit(:first_name, :last_name, :phone_number, :dl, :volunteer, :email, :password)
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
    <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@teacher.errors.count, "error") %>
        prohibited this user from being saved:
      </h2>
   
      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul></div>
    <% end %>

    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %><br><br>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %><br><br>
    <%= f.label :phone_number %><br>
    <%= f.telephone_field :phone_number %><br><br>
    <%= f.check_box :volunteer %><br>
    <%= f.label :volunteer, "Check box if you are a volunteer" %><br><br>
    <%= f.label :DL, "Please enter your Driver's Licence Number. All teachers will be subject to a background check." %><br>
    <%= f.number_field :dl %><br><br>
    <h3>Log In Info:</h3>
    <%= f.label :email %><br>
    <%= f.email_field :email %><br><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br><br>
    <%= f.submit class: "btn btn-primary" %><br><br>
<% end %> 

app/views/teachers/edit.html.erb
<h1>Edit <%= @teacher.first_name %>'s Profile</h1>
<%= render 'form'%>

app/views/teachers/index.html.erb
<h2> Teacher's Roster: </h2>
<ul>
<% @teachers.sort{|a,b| a.last_name <=> b.last_name}.each do |t| %>
    <div><%= link_to t.to_s, teacher_path(t) %></div><br>
<% end %>
</ul><br>

app/views/teachers/new.html.erb
<h1>Create a New Account</h1>
<%= render 'form' %>

<p>Already have an account? <%= link_to "Log In", login_path %></p>
<p><%= link_to "Return Home", root_path %></p>

app/views/teachers/show.html.erb
<h1> <%= @teacher.to_s %>'s Profile </h1>
<hr>

<h3>Volunteer Status: <%= @teacher.volunteer %></h3><br>
<% if @teacher.classroom.nil?%>
<i><%= link_to 'Add Your Classroom', new_classroom_path(@teacher.classroom) %></i><br>
<% else %>
<h3>Class: <%= link_to @teacher.classroom.title, classroom_path(@teacher.classroom) %></h3>
<% end %><br>

<p>Assignments:</p>
<% @teacher.assignments.each do |a| %>
  <div><li><%= link_to a.title, assignment_path(a) %></li></div>
<% end %><br>

<i><%= link_to 'New Assignment', new_teacher_assignment_path(@teacher) %></i><br><br>
<p><i><%= @teacher.last_updated %></i></p>
<p><%= link_to 'Update Profile', edit_teacher_path(@teacher) %></p>