config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  
  get '/auth/facebook/callback' => 'sessions#create'

  resources :assignments, :only => [:show, :index, :edit, :new, :create, :update]

  resources :parents, :only => [:show, :new, :edit, :create, :update]

  resources :children, :only => [:show, :index, :edit, :new, :create, :update]

  resources :classrooms, :only => [:show, :index, :edit, :new, :create, :update]
  resources :classrooms, :only => [:show] do 
    resources :children, :only => [:show, :index, :new, :edit]
  end

  resources :teachers, :only => [:show, :index, :edit, :new, :create, :update]
  resources :teachers, :only => [:show, :index] do 
    resources :assignments, :only => [:show, :index, :new, :edit, :update]
  end


  get '/children/search', to:'children#search'
  post '/children/search', to:'children#results'

  end

app/views/layouts/application.html.erb
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Sunday School</title>
    <%= favicon_link_tag %>
		<style type="text/css">
		
			body {
				margin:0;
				padding:0;
				font-family: .sansserif {
          font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        }
				line-height: 1.5em;
			}
			
			#header {
				background: #C9EAF3;
				height: 130px;
				text-align: center;
			}
			
			#header h1 {
				margin: 0;
				padding-top: 25px;
			}
			
			main {
				padding-bottom: 10050px;
				margin-bottom: -10000px;
				padding-top: 25px;
				float: left;
				width: 100%;
				background: #FDFDFO;
			}
			
			#footer {
				clear: left;
				width: 100%;
				background: #E1E1FF;
				text-align: center;
				padding: 4px 0;
			}
	
			#wrapper {
				overflow: hidden;
			}
						
			#content {
				margin-left: 25px; /* Same as 'nav' width */
				margin-right: 25px; /* Same as 'nav' width */
			}
			
			.innertube {
				margin: 25px; /* Padding for content */
				margin-top: 0;
			}
		
			p {
				color: #555;
			}
		
		</style>
	
	</head>
	
	<body>		

		<header id="header">
			<div class="innertube">
				<h1>Sunday School</h1><br>
				<% if current_teacher %><p><%= link_to 'Home', teacher_path(@current_user) %> | <%= link_to 'Logout', logout_path(session)%></p>
				<% end %><br>
			</div>
		</header>
		
		<div id="wrapper">
		
			<main>
				<div id="content">
					<div class="innertube">
						<body>
            <%= yield %>
            </body>
					</div>
				</div>
			</main></div>
		
		<footer id="footer">
      <div class="innertube">
	  <% if current_teacher %>
	  <i><p> Logged in as <%= current_teacher.email %><p></i>
		
		<% else %>
		<p><i>Sunday School WebApp</i></p>
        <% end %>
			</div>
		</footer>
	
	</body>
</html>

app/views/layouts/openapp.html.erb
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Sunday School</title>
    <%= favicon_link_tag %>
		<style type="text/css">
		
			body {
				margin:0;
				padding:0;
				font-family: .sansserif {
          font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        }
				line-height: 1.5em;
			}
			
			#header {
				background: #C9EAF3;
				height: 95px;
				text-align: center;
			}
			
			#header h1 {
				margin: 0;
				padding-top: 25px;
			}
			
			main {
				padding-bottom: 10050px;
				margin-bottom: -10000px;
				padding-top: 25px;
				float: left;
				width: 100%;
				background: #FDFDFO;
			}
			#nav {
				padding-bottom: 10010px;
				margin-bottom: -10000px;
				float: left;
				width: 230px;
				margin-left: -100%;
				background: #EBFFE5;
			}
			
			#footer {
				clear: left;
				width: 100%;
				background: #E1E1FF;
				text-align: center;
				padding: 4px 0;
			}
	
			#wrapper {
				overflow: hidden;
			}
						
			#content {
				margin-left: 230px; /* Same as 'nav' width */
				margin-right: 230px; /* Same as 'nav' width */
			}
			
			.innertube {
				margin: 25px; /* Padding for content */
				margin-top: 0;
			}
		
			p {
				color: #555;
			}
			nav ul {
				list-style-type: none;
				margin: 0;
				padding: 0;
			}
			
			nav ul a {
				color: darkgreen;
				text-decoration: none;
			}
		
		</style>
	
	</head>
	
	<body>		

		<header id="header">
			<div class="innertube">
				<h1>Sunday School</h1><br>
			</div>
		</header>
		
		<div id="wrapper">
		
			<main>
				<div id="content">
					<div class="innertube">
						<body>
            			<%= yield %>
            			</body>
					</div>
				</div>
			</main>
			<nav id="nav">
				<div class="innertube">
					<h3>OPTIONS:</h3>
					<ul>
						<li><%= link_to 'Home', teacher_path(@current_user) %></li><br>
						<li><%= link_to 'Classroom', classroom_path(@current_user) %></li><br>
						<li><%= link_to 'Assignments', teacher_assignments_path(@current_user) %></li><br>
						<li><%= link_to '- All Teachers', teachers_path(@current_user) %></li><br>
						<li><%= link_to '- All Classrooms', classrooms_path(@current_user) %></li><br>
						<li><%= link_to '- All Students', children_path(@current_user) %></li><br>
						<li><%= link_to 'Logout', logout_path(session)%></li><br>
					</ul>
				</div>
			</nav>
		
		</div>
		
		<footer id="footer">
      <div class="innertube">
	  <i><p> Logged in as <%= @current_user.email %><p></i>
		<p><i>Sunday School WebApp</i></p>
			</div>
		</footer>
	
	</body>
</html>